version: "3.9"

services:
  api:
    build:
      context: .
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - worker
    image: node:latest
    working_dir: /app
  worker:
    build:
      context: .
    command: npm run dev:worker
    volumes:
      - .:/app
    env_file:
      - .env
    image: node:latest
    working_dir: /app
  frontend:
    build:
      context: new-frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./new-frontend:/app
    env_file:
      - .env
    depends_on:
      - api
    image: node:latest
    working_dir: /app